name: 'weather_dbt'
version: '1.0'
profile: 'weather'
model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "/tmp/dbt_target"
clean-targets: ["/tmp/dbt_target"]

models:
  weather_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  weather_dbt:
    +schema: analytics
