name: 'weather_dbt'
version: '1.0'
profile: 'weather'
model-paths: ["models"]
target-path: "/tmp/dbt_target"
clean-targets: ["/tmp/dbt_target"]

models:
  weather_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
