version: 2

sources:
  - name: weatherapi
    description: "WeatherAPI.com raw data source"
    schema: dev
    tables:
      - name: raw_weather_data
        description: "Raw weather data from WeatherAPI.com bulk API"
        identifier: id
        loaded_at_field: recorded_at
        freshness:
          warn_after: {count: 2, period: minute}
          error_after: {count: 6, period: minute}
