name: 'weather_dbt'
version: '1.0'
profile: 'weather'
model-paths: ["models"]
seed-paths: ["seeds"]
log-path: "/tmp/dbt_logs"
clean-targets: ["/tmp/dbt_target"]

models:
  weather_dbt:
    staging:
      +materialized: view
      +tags: ['worldcup']
    intermediate:
      +materialized: view
      +tags: ['worldcup', 'live']
    marts:
      +materialized: table
      +tags: ['worldcup']

seeds:
  weather_dbt:
    +schema: analytics
