{
 "title": "Weather Monitoring Dashboard",
 "tags": [
  "weather",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "City",
    "query": "SELECT DISTINCT city FROM dev.stg_weather_data"
   }
  ]
 },
 "panels": [
  {
   "title": "Live Wind & Temperature Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    city,\n    (json_data::json->'query'->'location'->>'lat')::float as latitude,\n    (json_data::json->'query'->'location'->>'lon')::float as longitude,\n    temperature as temp,\n    (json_data::json->'query'->'current'->>'wind_degree')::int as wind_dir,\n    (json_data::json->'query'->'current'->>'wind_mph')::float as wind_speed,\n    recorded_at as time\nFROM dev.raw_weather_data \nWHERE (city, recorded_at) IN (\n    SELECT city, MAX(recorded_at) FROM dev.raw_weather_data GROUP BY 1\n)\nAND recorded_at >= $__timeFrom() AND recorded_at <= $__timeTo();"
    }
   ]
  },
  {
   "title": "Temperature Heatmap (24H)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    recorded_at as time,\n    city,\n    temperature\nFROM dev.stg_weather_data\nWHERE city IN ($city)\n  AND recorded_at >= $__timeFrom() AND recorded_at <= $__timeTo()\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Global Avg Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    AVG(temperature) as value,\n    recorded_at as time\nFROM dev.stg_weather_data\nWHERE recorded_at >= $__timeFrom() AND recorded_at <= $__timeTo()\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Wind Speed by City",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    city,\n    wind_speed as value,\n    recorded_at as time\nFROM dev.stg_weather_data\nWHERE recorded_at >= $__timeFrom() AND recorded_at <= $__timeTo()\nORDER BY time, city;"
    }
   ]
  },
  {
   "title": "Current City Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    city as metric,\n    temperature as value,\n    recorded_at as time\nFROM dev.stg_weather_data\nWHERE recorded_at = (SELECT MAX(recorded_at) FROM dev.stg_weather_data)\nORDER BY temperature;"
    }
   ]
  }
 ]
}