{
 "title": "Weather Dashboard",
 "tags": [ "weather" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Weather Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    city,\n    (json_data::json->'query'->'location'->>'lat')::float as latitude,\n    (json_data::json->'query'->'location'->>'lon')::float as longitude,\n    temperature as temp,\n    recorded_at as time\nFROM dev.raw_weather_data \nWHERE recorded_at >= NOW() - INTERVAL '1 hour'\nORDER BY recorded_at ASC;"
    }
   ]
  },
  {
   "title": "Current Temperatures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \n    city as metric,\n    temperature as value,\n    recorded_at as time\nFROM dev.stg_weather_data\nWHERE recorded_at >= NOW() - INTERVAL '24 hours'\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Global Avg Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    AVG(temperature) as value,\n    recorded_at as time\nFROM dev.stg_weather_data\nWHERE recorded_at >= NOW() - INTERVAL '24 hours'\nGROUP BY time\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    city,\n    wind_speed as value,\n    recorded_at as time\nFROM dev.stg_weather_data\nWHERE recorded_at >= NOW() - INTERVAL '24 hours'\nORDER BY time ASC, city;"
    }
   ]
  }
 ]
}